<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>문제해결 on 메모장</title><link>https://hsyang.net/troubleshootings/</link><description>Recent content in 문제해결 on 메모장</description><generator>Hugo -- gohugo.io</generator><language>ko</language><atom:link href="https://hsyang.net/troubleshootings/index.xml" rel="self" type="application/rss+xml"/><item><title>[문제 해결] AWS was not able to validate the provided access credentials</title><link>https://hsyang.net/troubleshootings/aws-credential-error/</link><pubDate>Mon, 18 Apr 2022 21:55:40 +0900</pubDate><guid>https://hsyang.net/troubleshootings/aws-credential-error/</guid><description>현상 Traceback (most recent call last): File &amp;#34;./aws.py&amp;#34;, line 19, in &amp;lt;module&amp;gt; {&amp;#39;Name&amp;#39;: &amp;#39;instance-state-name&amp;#39;, &amp;#39;Values&amp;#39;: [&amp;#39;running&amp;#39;]} File &amp;#34;/lib64/python3.6/site-packages/botocore/client.py&amp;#34;, line 386, in _api_call return self._make_api_call(operation_name, kwargs) File &amp;#34;/lib64/python3.6/site-packages/botocore/client.py&amp;#34;, line 705, in _make_api_call raise error_class(parsed_response, operation_name) botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials 원인 시스템 시간 동기화가 되어 있지</description></item><item><title>[문제 해결] Qt Quick 2 / QML - TypeError: Cannot read property</title><link>https://hsyang.net/troubleshootings/qt-type-error-cannot-read-property/</link><pubDate>Sun, 20 Mar 2022 11:20:08 +0900</pubDate><guid>https://hsyang.net/troubleshootings/qt-type-error-cannot-read-property/</guid><description>현상 아래 코드 실행 후 동적으로 List Item을 추가한 후, 삭제 시 다음과 같은 에러 메시지가 출력됨 main.qml:45: TypeError: Cannot read property &amp;#39;width&amp;#39; of null main.py import os from pathlib import Path import sys from PySide2.QtGui import QGuiApplication from PySide2.QtQml import QQmlApplicationEngine if __name__ == &amp;#34;__main__&amp;#34;:</description></item><item><title>[문제 해결] pyinstaller - OSError: Python library not found</title><link>https://hsyang.net/troubleshootings/pyinstaller-python-library-not-found/</link><pubDate>Fri, 18 Mar 2022 14:58:32 +0900</pubDate><guid>https://hsyang.net/troubleshootings/pyinstaller-python-library-not-found/</guid><description>현상 pyenv로 구성한 파이썬 가상환경에서 Qt5 파이썬 코드를 pyinstaller 빌드 시 아래와 같은 에러 발생 OSError: Python library not found: libpython3.8m.so, libpython3.8m.so.1.0, libpython3.8.so.1.0, libpython3.8mu.so.1.0 This would mean your Python installation doesn&amp;#39;t come with proper library files. This usually happens by missing development package, or unsuitable</description></item><item><title>[문제 해결] Qt Quick 2 / QML - Unable to assign QQuickWindowQmlImpl to QQuickItem</title><link>https://hsyang.net/troubleshootings/qt-unable-to-assign-qquickwindowqmlimpl-to-qquickitem/</link><pubDate>Fri, 18 Mar 2022 14:58:32 +0900</pubDate><guid>https://hsyang.net/troubleshootings/qt-unable-to-assign-qquickwindowqmlimpl-to-qquickitem/</guid><description>현상 아래 코드 실행 시 다음과 같은 에러가 발생하며 MouseArea 적용이 되지 않음 main.qml:13:9: Unable to assign QQuickWindowQmlImpl to QQuickItem main.py import os from pathlib import Path import sys from PySide2.QtGui import QGuiApplication from PySide2.QtQml import QQmlApplicationEngine if __name__ == &amp;#34;__main__&amp;#34;: app = QGuiApplication(sys.argv) engine = QQmlApplicationEngine() engine.load(os.fspath(Path(__file__).resolve().parent / &amp;#34;main.qml&amp;#34;)) if not engine.rootObjects(): sys.exit(-1)</description></item></channel></rss>